### ISSUE TITLE
希望增加打印或提示信息

### ISSUE THREAD

**Issue by MrWaterr** [takagisanmie/NIKKEAutoScript#11]
在部分依赖组件进行下载时，希望增加提示信息。在第一次加载时，若在cnocr相关组件下载未完成的情况下关闭，会导致cnocr 运行报错 file is not a zip file。

**Comment by takagisanmie** [comment]
旧版是需要下载cnocr的模型，在新版中是直接读取本地的
目前新版功能还没写完，麻烦耐心等待，因为是完全重构过的
不再使用vue编写ui，改为使用pywebio渲染，这样也能在线更新，不再需要来github下载更新包了

**Comment by takagisanmie** [comment]
所以我不打算再修改或新增旧版功能，因为实在是太烂了，见谅
