### ISSUE TITLE
v0.07，打开win-unpacked中的exe，显示“Failed to load resource”

### ISSUE THREAD

**Issue by xiaglino** [takagisanmie/NIKKEAutoScript#13]
![image](https://user-images.githubusercontent.com/90585998/235402307-f819b9f1-af46-4677-938d-7b1e01514f80.png)

**Comment by takagisanmie** [comment]
加下联系方式吧

**Comment by xiaglino** [comment]
问题解决了，卸载后重启电脑，重新解压了一遍，并多次运行updater
我用的也是7z解压的，应该不是解压软件的问题，现在我无法复现之前的error了

**Comment by takagisanmie** [comment]
那检查更新什么的都没问题吧？

**Comment by xiaglino** [comment]
运行updater.bat来更新是没问题的，还没有试过集成的。
检查更新功能也没问题。
![image](https://user-images.githubusercontent.com/90585998/235433873-c318d1d2-041f-4ac7-84d2-310f7b0c00af.png)

**Comment by takagisanmie** [comment]
好的！

**Comment by takagisanmie** [comment]
你好，可以加一下划水群 823265807，也方便告知bug

**Comment by takagisanmie** [comment]
<img width="167" alt="Snipaste_2023-05-04_00-52-04" src="https://user-images.githubusercontent.com/71818138/236199849-fd31ec54-f304-4024-8278-28a7e0ee29c5.png">
