### ISSUE TITLE
咨询无法运作

### ISSUE THREAD

**Issue by fimdo809** [takagisanmie/NIKKEAutoScript#14]
[2023-05-04_nkas.txt](https://github.com/takagisanmie/NIKKEAutoScript/files/11398638/2023-05-04_nkas.txt)
咨询设定有妮姬但是没办法运作
活動story2也出现错误 不知道是不是我设定错了

**Comment by takagisanmie** [comment]
你确定用的最新版吗？

**Comment by takagisanmie** [comment]
那个竞技场商店不能填写‘fire’，燃烧代码的技能书应该是‘FIRE_CODE’

**Comment by fimdo809** [comment]
![image](https://user-images.githubusercontent.com/129553438/236247205-8fe588be-b541-41c3-9cfa-63e6c1a35d5b.png)
我諮詢是這樣打的

**Comment by takagisanmie** [comment]
你能接受什么联系方式呢，这样交流不是很方便

**Comment by takagisanmie** [comment]
我明白了，是并不是NIKKE LIST为空，NIKKE LIST只有在调用的情况下才会输出
VISITED NIKKE LIST 是遍历过的NIKKE的集合

**Comment by fimdo809** [comment]
我不是中国人所以我不确定有什么联系方式

**Comment by takagisanmie** [comment]
你的NIKKE开的是最高画质吗？

**Comment by fimdo809** [comment]
是台灣人

**Comment by takagisanmie** [comment]
那telegram也行

**Comment by fimdo809** [comment]
加我 @fimdo809

**Comment by fimdo809** [comment]
![Screenshot_20230504-234010](https://user-images.githubusercontent.com/129553438/236258360-5b38e15c-8ef5-4a63-b603-5741a55f9737.png)
