### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by WakPd** [takagisanmie/NIKKEAutoScript#16]
Hello, i tried to install-re-install, unzip and test and update multiple times but always the same issue.
![Capture d'écran 2023-05-23 151613](https://github.com/takagisanmie/NIKKEAutoScript/assets/101495954/a3d65c38-fdc6-4627-b25d-2516e244597f)
![Capture d'écran 2023-05-23 151539](https://github.com/takagisanmie/NIKKEAutoScript/assets/101495954/f5718157-cca4-4c8a-844a-379dda918fa8)

**Comment by takagisanmie** [comment]
Could you try to press Ctrl+R to reload the application ？
Perhaps it's not completely loaded.

**Comment by takagisanmie** [comment]
I saw your Discord account. Let's talk conveniently on it, okay

**Comment by takagisanmie** [comment]
Can we talk conveniently on Telegram or Discord?

**Comment by zzb-yy** [comment]
I also have this problem，Just press it a few more times， Ctrl + r

**Comment by WakPd** [comment]
Hello, thank you for trying to help, i tried your suggestion, update and run then try to press Ctrl + r many times, but it still don't show anything even after many restart. But i appreciate the help.

**Comment by zzb-yy** [comment]
When you open naks, open the webpage and enter 127.0.0.1:12271 to see if there is an interface? If there is, it can be operated through the webpage, which is a little more troublesome

**Comment by WakPd** [comment]
Sadly there's nothing, but if there's nothing that also means that the option is not activated so, there probably a way to activate it automatically while launching the app, i will try to find a solution to this.

**Comment by zzb-yy** [comment]
Try installing dependencies? I don't know if you have done this before
Q2: The main program has no content, only the top bar
A2: It may be that a dependency is missing, you can manually install the dependencies in requirements.txt through CMD

**Comment by WakPd** [comment]
I tried but even that didn't work sadly

**Comment by Celtica3** [comment]
can you make sure a command line interface made available first so that it is possible for us to test things

**Comment by WakPd** [comment]
I don't understand what you mean

**Comment by Theodoric99** [comment]
Had the same issue as OP, installed the requirements but blank screen still persists, I wonder if it's due to the torch version? Installed 2.1.0 because apparently 1.12.1 does not exist. Opening a webpage to enter 127.0.0.1:12271 returns a blank screen also. Any other suggestions are welcome
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/107056523/5e33ee27-9c99-4261-997f-a545c520aa69)
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/107056523/48897e5e-dd84-4505-af96-000357fa6cea)

**Comment by 7thwarlord** [comment]
I got the dependency's installed using python 3.9.13 for anyone having trouble with installing the requirements.txt. Still got the same error as op, tried on win 10 and win 11 machine

**Comment by totallynotaguynon** [comment]
I had the same error it got solved if I tried to manually run C:\NKAS\python-3.9.13-embed-amd64\python.exe gui.py and the reload the .exe

**Comment by WakPd** [comment]
> I had the same error it got solved if I tried to manually run C:\NKAS\python-3.9.13-embed-amd64\python.exe gui.py and then reload the .exe

It worked Thank you.
