### ISSUE TITLE
活动似乎只会打一次

### ISSUE THREAD

**Issue by QuinLi** [takagisanmie/NIKKEAutoScript#17]
首先感谢大佬！

今天刚下载。发现执行活动任务时似乎只执行了一次。附上截图：
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/82415595/46b22b80-b2d4-42fa-890f-1ca16f6f5155)
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/82415595/22e7dd3f-07f5-410c-976f-2dfd4af302fc)

**Comment by takagisanmie** [comment]
可以加一下qq群，也方便交流一点，把今天的日志发给我看一下呢，在log文件夹里
