### ISSUE TITLE
咨询可能存在问题

### ISSUE THREAD

**Issue by AkashiEi** [takagisanmie/NIKKEAutoScript#18]
看到个warning 为
WARNING  11:26:09.871 │ Unexpected ocr result: 8/ 
SHA1是9e9d3c6

**Comment by takagisanmie** [comment]
似乎是在识别咨询次数，但是在5月末的时候就已经改为别的方式了
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/71818138/1d721422-e560-4e0a-916f-306a72c0fc8f)

**Comment by takagisanmie** [comment]
可以加一下qq群，或者我个人的qq也行，交流方便一点

**Comment by AkashiEi** [comment]
找到问题了（原来是点检查更新不会自动更新 是我眼瞎了
