### ISSUE TITLE
模拟器又可以正常运行游戏

### ISSUE THREAD

**Issue by Gameforfun007** [takagisanmie/NIKKEAutoScript#19]
2023.10.16日实测，模拟器又能使用了，求大佬继续更新

**Comment by takagisanmie** [comment]
脚本一直都能用的

**Comment by Gameforfun007** [comment]
> 脚本一直都能用的

咨询好像不能识别新的妮姬，新的活动也无法识别，还是这些可以自己手动修改？

**Comment by takagisanmie** [comment]
娜迦，蒂亚等会更新，活动停更了，改起来太累了

**Comment by Gameforfun007** [comment]
> 娜迦，蒂亚等会更新，活动停更了，改起来太累了

好吧，再次感谢大佬写这些脚本
