### ISSUE TITLE
提示File is not a zip file，正在尝试重启ADB

### ISSUE THREAD

**Issue by Arubatorion** [takagisanmie/NIKKEAutoScript#2]
第一次打开没事，第二次打开就这样了
![QQ图片20230305205736](https://user-images.githubusercontent.com/20701540/222961829-e2589b50-2af7-4256-a227-c9da04876f70.png)

**Comment by takagisanmie** [comment]
麻烦把cmd窗口往上滑点，让File is not a zip file这一行在窗口可视范围的最底部，信息有点少

**Comment by Arubatorion** [comment]
> 麻烦把cmd窗口往上滑点，让File is not a zip file这一行在窗口可视范围的最底部，信息有点少

![QQ图片20230306122807](https://user-images.githubusercontent.com/20701540/223019796-d750945a-8227-419e-9066-4b71c64bff2e.png)
我自己搞好了，又出现这个

**Comment by takagisanmie** [comment]
这个问题应该是因为nikke是从google play下载的，下载的nikke的原因
可以试试从qooapp下载
