### ISSUE TITLE
咨询完成异常

### ISSUE THREAD

**Issue by johnson50313** [takagisanmie/NIKKEAutoScript#20]
咨询完成后，程式都会自己停止，必须手动重新点选开始按钮

[2024-01-23.txt](https://github.com/takagisanmie/NIKKEAutoScript/files/14016417/2024-01-23.txt)
![擷取](https://github.com/takagisanmie/NIKKEAutoScript/assets/118783940/3ed30df0-c13d-4dd3-896d-7c903b656429)

**Comment by takagisanmie** [comment]
这个我暂时没搞明白是什么问题
