### ISSUE TITLE
matplotlib报错

### ISSUE THREAD

**Issue by Anfies** [takagisanmie/NIKKEAutoScript#29]
作者大大您好，请问这个报错是啥情况，是需要我在base环境里更新matplotlib版本吗？
![屏幕截图 2024-05-31 105831](https://github.com/takagisanmie/NIKKEAutoScript/assets/132662924/3e4527d1-9e93-41e2-bdf1-1a4a6651e2ee)
![屏幕截图 2024-05-31 105856](https://github.com/takagisanmie/NIKKEAutoScript/assets/132662924/c0c849c3-812e-4267-ab75-83b4554d5859)

**Comment by Anfies** [comment]
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/132662924/434f5297-50d6-44e1-bb0a-ad12f8bd07dc)

**Comment by Anfies** [comment]
程序是会调用python-3.9.13-embed-amd64文件夹里面的包还是系统环境里的包

**Comment by Anfies** [comment]
我又试了一下，用pip uninstall matplotlib把系统基础环境里的包卸载之后就好了。

**Comment by Anfies** [comment]
现在其他功能都正常，这个咨询的界面为啥空空的，不能设定咨询妮姬
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/132662924/ba90db5a-d05c-45bf-9ade-38c805dd7af1)

**Comment by takagisanmie** [comment]
这个咨询，只需要收藏要咨询的nikke就行了

**Comment by Anfies** [comment]
> 这个咨询，只需要收藏要咨询的nikke就行了

ok

**Comment by Anfies** [comment]
能正常用了，就是咨询完进新人竞技场可能会中断。需要重新开一下

**Comment by takagisanmie** [comment]
应该是要下载一下依赖，开全局代理试试

**Comment by Anfies** [comment]
> 应该是要下载一下依赖，开全局代理试试

ok

**Comment by Anfies** [comment]
qq群可以加一下吗，之前加了没有回应
![QQ图片20210828230206](https://github.com/takagisanmie/NIKKEAutoScript/assets/132662924/c72cc395-3bc3-4570-82d1-7919029e8714)

**Comment by takagisanmie** [comment]
开了，再申请下吧

**Comment by Anfies** [comment]
3q
