### ISSUE TITLE
艹！写的太好了！

### ISSUE THREAD

**Issue by xiaglino** [takagisanmie/NIKKEAutoScript#3]
有些小问题：
1、当模拟室处于已经开始状态，此时打开脚本进行模拟室的内容，无法继续进行或者退出重新进行任务。
2、当活动关卡次数已经耗尽，再打开脚本运行活动的内容，就开始遍历无法打的关卡，可以添加一个活动关卡次数识别。
3、希望能够提供类似MAA的功能，比如抄作业来打关，捡地图的小垃圾，甚至是配对来打竞技场。当然，这就需要一些作业组啥的了。
4、希望添加解放自动化的内容。
5、希望能够自动领取pass、每日任务、每周任务、成就、邮件等等；要是可以的话，希望能够提供回归任务的内容。
6、希望能够添加联盟战内容。
7、希望能够自动升级前五的等级，规避紫卡升级，当前五无法升级，能够自动给剩余金卡、紫卡、蓝卡升级。
8、希望能够程序封装完整，提供一个exe文件，换上好看的海伦头像。

PS：
给个赞助渠道吧，比如阿B出道直播写代码，白用有点虚。：）

**Comment by takagisanmie** [comment]
目前我正在改成在720x1280下使用，还需要一段时间，还麻烦耐心等待
1.已经改进了
2.逻辑里有识别次数，应该是没有写好
3.捡垃圾或过关需要地图识别，对我来说挺难的，我的技术没有你想得那么好。。
4.后面改进
5.单独领取奖励没问题，以及我需要一个带有回归任务的账号。。
你是说要完成回归任务吗？
6.如果是自动出刀的话，那需要联盟战开启，而且做不了很快
7.升级是没什么问题，但是，不是有同步器吗？
8.主程序是打包的，但后端在打包后无法使用。。

赞助就算了，我写的什么水平，我还是有数的，有人用我就很开心了！！
出道就算了，那不是给人看笑话吗。。

最后感谢你写的这么多意见！！，虽然我很大可能无法完成全部，真的非常感谢！！
