### ISSUE TITLE
尝试无数次重新解压更新后依旧 Failed to load resource

### ISSUE THREAD

**Issue by 2unforest** [takagisanmie/NIKKEAutoScript#30]
两个文件都是下载好了的，修改了gitproxy更新的，每次看见控制台都更新好了在检查依赖然后消失，不知道哪个步骤出了问题，运行exe依旧出现标题所述的报错，辛苦大佬替小弟解惑。

**Comment by 2unforest** [comment]
INFO     2024-06-01 20:38:34.131 │ pyw_name: updater
═════════════════════════════════════════════════ SHOW DEPLOY CONFIG ══════════════════════════════════════════════════
INFO     2024-06-01 20:38:34.278 │ SHOW DEPLOY CONFIG
INFO     2024-06-01 20:38:34.280 │ Rest of the configs are the same as default
INFO     2024-06-01 20:38:34.282 │ <<< RUN UPDATE >>>
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                        UPDATE
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
══════════════════════════════════════════════════════ GIT INIT ═══════════════════════════════════════════════════════
INFO     2024-06-01 20:38:34.286 │ GIT INIT
INFO     2024-06-01 20:38:34.289 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in C:/Users/Administrator/Downloads/NKAS/.git/
INFO     2024-06-01 20:38:34.319 │ [ success ]
════════════════════════════════════════════════════ SET GIT PROXY ════════════════════════════════════════════════════
INFO     2024-06-01 20:38:34.324 │ SET GIT PROXY
INFO     2024-06-01 20:38:34.325 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" config
         --local http.proxy http://127.0.0.1:7897
INFO     2024-06-01 20:38:34.345 │ [ success ]
INFO     2024-06-01 20:38:34.348 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" config
         --local https.proxy http://127.0.0.1:7897
INFO     2024-06-01 20:38:34.371 │ [ success ]
═════════════════════════════════════════════════ SET GIT REPOSITORY ══════════════════════════════════════════════════
INFO     2024-06-01 20:38:34.374 │ SET GIT REPOSITORY
INFO     2024-06-01 20:38:34.376 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" remote
         set-url origin https://github.com/takagisanmie/NIKKEAutoScript
error: No such remote 'origin'
INFO     2024-06-01 20:38:34.396 │ [ allowed failure ], error_code: 2
INFO     2024-06-01 20:38:34.399 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" remote add
         origin https://github.com/takagisanmie/NIKKEAutoScript
INFO     2024-06-01 20:38:34.423 │ [ success ]
═══════════════════════════════════════════════ FETCH REPOSITORY BRANCH ═══════════════════════════════════════════════
INFO     2024-06-01 20:38:34.427 │ FETCH REPOSITORY BRANCH
INFO     2024-06-01 20:38:34.429 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" fetch origin
         master
remote: Enumerating objects: 4514, done.
remote: Counting objects: 100% (399/399), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 4514 (delta 346), reused 339 (delta 314), pack-reused 4115
Receiving objects: 100% (4514/4514), 268.32 MiB | 11.85 MiB/s, done.
Resolving deltas: 100% (2888/2888), done.
From https://github.com/takagisanmie/NIKKEAutoScript
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
INFO     2024-06-01 20:39:00.669 │ [ success ]
INFO     2024-06-01 20:39:00.672 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" reset --hard
         origin/master
HEAD is now at 465fbcb fix: Mission Pass
INFO     2024-06-01 20:39:01.637 │ [ success ]
INFO     2024-06-01 20:39:01.640 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" pull
         --ff-only origin master
From https://github.com/takagisanmie/NIKKEAutoScript
 * branch            master     -> FETCH_HEAD
Already up to date.
INFO     2024-06-01 20:39:04.424 │ [ success ]
════════════════════════════════════════════════════ SHOW VERSION ═════════════════════════════════════════════════════
INFO     2024-06-01 20:39:04.427 │ SHOW VERSION
INFO     2024-06-01 20:39:04.429 │ "C:/Users/Administrator/Downloads/NKAS/toolkit/Git/mingw64/bin/git.exe" --no-pager
         log --no-merges -1
commit 465fbcb630cbc41eecf213ea6896766eaf568329 (HEAD -> master, origin/master)
Author: takagi <3197137842@qq.com>
Date:   Sat Jun 1 12:59:07 2024 +0800

    fix: Mission Pass
INFO     2024-06-01 20:39:04.452 │ [ success ]
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                  UPDATE DEPENDENCIES
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════════ CHECK PYTHON ═════════════════════════════════════════════════════
INFO     2024-06-01 20:39:04.458 │ CHECK PYTHON
INFO     2024-06-01 20:39:04.461 │ "C:/Users/Administrator/Downloads/NKAS/python-3.9.13-embed-amd64/python.exe"
         --version
Python 3.9.13
INFO     2024-06-01 20:39:04.476 │ [ success ]
═════════════════════════════════════════════════ UPDATE DEPENDENCIES ═════════════════════════════════════════════════
INFO     2024-06-01 20:39:04.480 │ UPDATE DEPENDENCIES
INFO     2024-06-01 20:39:04.481 │ "C:/Users/Administrator/Downloads/NKAS/python-3.9.13-embed-amd64/python.exe" -m pip
         install -r requirements.txt --disable-pip-version-check
Requirement already satisfied: uvicorn==0.21.1 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 1)) (0.21.1)
Requirement already satisfied: starlette==0.26.1 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 2)) (0.26.1)
Requirement already satisfied: pywebio==1.7.1 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: websockets==10.4 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 4)) (10.4)
Requirement already satisfied: pyyaml==6.0 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 5)) (6.0)
Requirement already satisfied: torch==1.12.1 in c:\users\administrator\downloads\nkas\python-3.9.13-embed-amd64\lib\site-packages (from -r requirements.txt (line 6)) (1.12.1)
C


上面是一段logs

**Comment by takagisanmie** [comment]
这个问题我也不知道是因为什么，你试试这样吧
#13 
![image](https://github.com/takagisanmie/NIKKEAutoScript/assets/71818138/a5ce37f6-321e-4966-ba73-f1a65af38279)

**Comment by 2unforest** [comment]
还是不知道哪里出问题了，只是最开始前面手动装了一下那些依赖，印象中cmd里面装到torch的时候说没有这样一个版本，然后我就装了一个2.0.0的不知道是不是这个问题。qq群搜不到了

**Comment by takagisanmie** [comment]
开了，再申请下了
