### ISSUE TITLE
调度器按开始过后啥都没发生

### ISSUE THREAD

**Issue by keithwkx** [takagisanmie/NIKKEAutoScript#38]
调度器按开始过后啥都没发生。其本上按了3秒就变回开始

**Comment by takagisanmie** [comment]
在任务管理器结束所有的python.exe，然后重启脚本试试

**Comment by keithwkx** [comment]
@takagisanmie 还是不行。试问是否有discord之类的可以联系一下吗？

**Comment by keithwkx** [comment]
@takagisanmie https://i.imgur.com/d6ogpco.gif 您看看，目前这样

**Comment by takagisanmie** [comment]
你运行main.py，看一下报了什么错误

**Comment by keithwkx** [comment]
WARNING  2024-07-16 16:01:53.672 │ Unable to get device orientation, assume it is normal
INFO     2024-07-16 16:01:53.674 │ [Device Orientation] 0 (Normal)
ERROR    2024-07-16 16:01:56.731 │ ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20193): Max retries
         exceeded with url: /screenshot?width=720&height=1280 (Caused by
         NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E268F6910>: Failed to establish a new
         connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by keithwkx** [comment]
好像是无法锁定模拟器？

**Comment by keithwkx** [comment]
刚刚main.py跑了起来。模拟器自己动了。就只是开了nkas无法开始

**Comment by keithwkx** [comment]
没事了，我直接跑python不用原本包括的gui就可以了
![image](https://github.com/user-attachments/assets/0625d2cc-19f3-4f2a-a758-8a6179ea9e68)
