### ISSUE TITLE
支持PC端吗

### ISSUE THREAD

**Issue by xianyu1124** [takagisanmie/NIKKEAutoScript#4]
现在用模拟器比较少了，一般都是用PC端，不知道是否支持横屏和PC端，希望能公开代码或者直播有个赞助渠道，或者开个群让有能力的人协助维护，很好的一款软件，可能刚起步暂不满足我的需求，期待后续更新

**Comment by takagisanmie** [comment]
你好，不能支持pc端的，因为我找不到可以让NIKKE在后台运行时进行操作的方法
我写这个的本质是想，在自动做任务时，可以做自己的事
公开代码。。
代码在master分支啊，我开仓库时弄错了，而且源码在Releases里也有，也不知道怎么移到main分支
直播和赞助就算了，我什么水平，我还是有数的
开群的话，我没这方面的经验，也不清楚有没有必要

**Comment by takagisanmie** [comment]
还有就是我现在打特殊拦截的火车时才用pc的，平时都是模拟器了
pc端的脚本，我记得有大佬做了 https://bbs.nga.cn/read.php?tid=35586169 这个是链接

**Comment by xianyu1124** [comment]
刚准备回复可以参考一下ALAS，发现您已经写了鸣谢，很好的一款脚本，之前找了很久想挂机然后做点别的事，但是没有发现有人写这款游戏的自动任务，期待后续的更新和优化。（感觉如果是一个人的话压力会很大，比如活动这种）

**Comment by xianyu1124** [comment]
> 还有就是我现在打特殊拦截的火车时才用pc的，平时都是模拟器了 pc端的脚本，我记得有大佬做了 https://bbs.nga.cn/read.php?tid=35586169 这个是链接

谢谢大佬，已给start，期待后续优化

**Comment by takagisanmie** [comment]
非常感谢！！我也不是什么大佬，就是个臭造轮子的

**Comment by xianyu1124** [comment]
感觉可以弄个小群，及时反馈BUG之类的，虽然不知道有多少人在用

**Comment by takagisanmie** [comment]
等真的有这个必要时再弄吧。。现在感觉没什么必要，我看网盘下载人数只有十多个

**Comment by xianyu1124** [comment]
github的会比较多吧，毕竟我就是从github直接下载的

**Comment by takagisanmie** [comment]
是吗，毕竟不是每个人都愿意折腾。。
