### ISSUE TITLE
运行一半会被官方发现是脚本是咋回事呢

### ISSUE THREAD

**Issue by tyzdr9** [takagisanmie/NIKKEAutoScript#40]

**Comment by takagisanmie** [comment]
具体是什么，被踢下线吗

**Comment by tyzdr9** [comment]
是的，说疑似脚本或者非官方客户端

**Comment by takagisanmie** [comment]
你用的什么模拟器

**Comment by tyzdr9** [comment]
用的蓝叠，用其他模拟器就没问题吗

**Comment by takagisanmie** [comment]
试试雷电模拟器国际版 9.0.61，安装时语言要选繁体中文

**Comment by tyzdr9** [comment]
繁体中文的识别位置好像有问题，任务都会卡住（一直点不存在按钮的地方），简体中文的雷电模拟器无问题了。

**Comment by takagisanmie** [comment]
现在得用 https://www.bluestacks.cn/ 5.20.101.6503 Pie 64-bit 了，雷电模拟器已经进不去了

**Comment by GABRRIES** [comment]
> 现在得用 https://www.bluestacks.cn/ 5.20.101.6503 Pie 64-bit 了，雷电模拟器已经进不去了

今天也弹提示了，这波下手够狠啊

**Comment by anxingyny** [comment]
蓝叠今天被检测了 有解决方法吗佬
