### ISSUE TITLE
LDPlayer doesnt work anymore

### ISSUE THREAD

**Issue by totallynotaguynon** [takagisanmie/NIKKEAutoScript#42]
![image](https://github.com/user-attachments/assets/5b4e5486-f80a-41b8-9a77-b9e6bb0a4bc0)
I'm gonna assume this is the end of it? Or is there maybe some setting that can be tweaked to make it work?

**Comment by takagisanmie** [comment]
I encountered the same problem, and I think no method can make it work at present

**Comment by totallynotaguynon** [comment]
@takagisanmie managed to "make" it work, or well found why it's getting blocked, the app now is trying to detect and adb wireless bridge, proof is that I tried to use it on my phone through USB adb and it worked, now I don't know how would it be possible to implement it on LDPlayer maybe with some external tools that can hide the active connection perhaps.

I tried both wireless debugging and usb debugging for phone
Wireless got flagged, USB didn't.

**Comment by takagisanmie** [comment]
I have some good news for you
https://www.bluestacks.cn/ (no ads) or https://www.bluestacks.com/download.html (have a lot of ads) 
This emulator can log in to NIKKE and the version is 5.20.101.6503 Pie 64-bit

![P5TD0EE ~ H{7O3$N~}}$X](https://github.com/user-attachments/assets/5f28125d-0235-4930-98a7-69c5da5961b3)

**Comment by totallynotaguynon** [comment]
@takagisanmie nice, you should censor your name though, be careful!
