### ISSUE TITLE
咨询卡在 [Opportunity remain] True   

### ISSUE THREAD

**Issue by SummerDiver** [takagisanmie/NIKKEAutoScript#44]
不断检查是否还有次数，手动点进去一个以后才会开始进行，但进行到没有次数时依然还是会不停下一页，不会自动结束任务
顺便Q群似乎又搜不到了，是我的问题吗

**Comment by takagisanmie** [comment]
脚本保持最新版，nikke画面设置要打开`光晕效果`和`颜色分级`，咨询至少收藏（点那个星）一个角色，nikke显示语言为简体中文，以上都不行请用模拟器截图并把原图发给我，在卡住的位置截图
