### ISSUE TITLE
咨询卡在选角介面

### ISSUE THREAD

**Issue by johnson50313** [takagisanmie/NIKKEAutoScript#49]
CONVERSATION                                  

    ════════════════════════════════════════════════════════════════════════════════

    INFO     07:28:08.597 │ <<< UI ENSURE >>>                                       

    INFO     07:28:08.600 │ UI get current page                                     

    INFO     07:28:08.603 │ [UI] page_shop                                          

    INFO     07:28:08.605 │ Goto page_conversation                                  

    INFO     07:28:08.606 │ <<< UI GOTO PAGE_CONVERSATION >>>                       

    INFO     07:28:08.702 │ Page switch: page_shop -> page_main                     

    INFO     07:28:08.703 │ Click (  41, 1207) @ GOTO_BACK                          

    INFO     07:28:11.206 │ Page switch: page_main -> page_team                     

    INFO     07:28:11.208 │ Click ( 107, 1234) @ MAIN_GOTO_TEAM                     

    INFO     07:28:15.218 │ Page switch: page_main -> page_team                     

    INFO     07:28:15.220 │ Click ( 107, 1234) @ MAIN_GOTO_TEAM                     

    INFO     07:28:16.855 │ Page switch: page_team -> page_conversation             

    INFO     07:28:16.857 │ Click ( 424,  155) @ TEAM_GOTO_CONVERSATION             

    INFO     07:28:19.125 │ Page arrive: page_conversation                          

    INFO     07:28:19.129 │ [Opportunity remain] True                               

    INFO     07:28:19.130 │ <<< START A CONVERSATION >>>                            

    INFO     07:28:19.136 │ [Opportunity remain] True                               

    INFO     07:28:20.546 │ [Opportunity remain] True                               

    INFO     07:28:21.937 │ [Opportunity remain] True                               

    INFO     07:28:23.341 │ [Opportunity remain] True                               

    INFO     07:28:24.741 │ [Opportunity remain] True                               

    INFO     07:28:26.137 │ [Opportunity remain] True                               

    INFO     07:28:27.537 │ [Opportunity remain] True                               

    INFO     07:28:28.936 │ [Opportunity remain] True                               

    INFO     07:28:30.324 │ [Opportunity remain] True                               

    INFO     07:28:31.707 │ [Opportunity remain] True                               

    INFO     07:28:33.093 │ [Opportunity remain] True                               

    INFO     07:28:34.582 │ [Opportunity remain] True                        
![image](https://github.com/user-attachments/assets/3cd30d38-007b-458a-ac98-1eb8036c0483)

**Comment by takagisanmie** [comment]
修复了
