### ISSUE TITLE
黑窗能否隐藏或者集成到软件内

### ISSUE THREAD

**Issue by xianyu1124** [takagisanmie/NIKKEAutoScript#5]
每次打开会有一个黑窗口，已经手误关了三次了。。。。然后就断开了

**Comment by takagisanmie** [comment]
目前可以在设置中的‘NKAS设置’中隐藏控制台，不过隐藏后，再关闭主程序，后端并不会关闭，需要在任务管理器中结束python.exe，我后面看看应该怎么改进

**Comment by takagisanmie** [comment]
不小心关掉了的话，可以单独启动runNKAS-Python.bat

**Comment by xianyu1124** [comment]
还有就是不支持横屏了。。。突然不太适应。希望优化几个地方望采纳（1、新人竞技场一般都是根据战斗力来打，是否能加上战力识别，只打超过的，没有就刷新。2、爬塔的时候进入战斗不知道为啥会直接放弃战斗？3、打模拟室的时候能否让它随机选一个属性，不然Lv5难度有点打不过。）谢谢

**Comment by takagisanmie** [comment]
1.后面我看看怎么改，主要是ocr效果不是很理想
2.因为在‘设置-企业塔’中开启了‘只完成每日任务，在进入后退出’的选项
3.你是说在战斗结束后没有选取效果吗，我写了一些有用的，如果是没有识别到的话
我后面再改改

**Comment by xianyu1124** [comment]
emmmm确实没有选择效果，可能会增加工作量，如果随机选择效果，满8个以后再选择会出现替换情况，这样就要再加一个优先级了，在OCR不理想的情况下，这样很容易会出错。

**Comment by takagisanmie** [comment]
如果是满了的话，会直接不选择的
