### ISSUE TITLE
卡新人竞技场介面

### ISSUE THREAD

**Issue by johnson50313** [takagisanmie/NIKKEAutoScript#54]
INFO     07:10:55.512 │ Reuse forward: ForwardItem(serial='emulator-5554',      
         local='tcp:20413', remote='tcp:53516')                                 

    INFO     07:10:55.567 │ <<< UI ENSURE >>>                                       

    INFO     07:10:55.568 │ UI get current page                                     

    INFO     07:10:55.651 │ Unknown ui page                                         

    INFO     07:10:55.655 │ Click ( 196, 1208) @ GOTO_MAIN                          

    INFO     07:10:55.657 │ <<< MINITOUCH INIT >>>                                  

    INFO     07:10:55.681 │ [Device Orientation] 0 (Normal)                         

    INFO     07:10:55.683 │ Reuse forward: ForwardItem(serial='emulator-5554',      
         local='tcp:20567', remote='localabstract:minitouch')                   

    INFO     07:10:55.722 │ v 1                                                     

    INFO     07:10:55.725 │ ^ 10 1279 719 2                                         

    INFO     07:10:55.726 │ $ 8716                                                  

    INFO     07:10:55.727 │ minitouch running on port: 20567, pid: 8716             

    INFO     07:10:55.727 │ max_contact: 10; max_x: 1279; max_y: 719; max_pressure: 
         2                                                                      

    INFO     07:10:56.056 │ [UI] page_rookie_arena                                  

    INFO     07:10:56.057 │ Goto page_arena                                         

    INFO     07:10:56.059 │ <<< UI GOTO PAGE_ARENA >>>                              

    INFO     07:10:56.147 │ Page switch: page_rookie_arena -> page_arena            

    INFO     07:10:56.148 │ Click (  41, 1207) @ GOTO_BACK                          

    INFO     07:10:57.044 │ Page arrive: page_arena                                 

    INFO     07:10:57.094 │ Click ( 114,  673) @ ARENA_GOTO_ROOKIE_ARENA            

    INFO     07:10:59.587 │ [Free opportunities remain] True                        

    INFO     07:10:59.588 │ <<< START A COMPETITION >>>                             

    INFO     07:10:59.589 │ [Free opportunities remain] True                        

    INFO     07:10:59.641 │ Click ( 580, 1080) @ START_COMPETITION                  

    INFO     07:11:00.090 │ Click ( 490, 1046) @ INTO_COMPETITION                   

![image](https://github.com/user-attachments/assets/5485524d-bb21-4894-a691-92b4d7457db9)

**Comment by takagisanmie** [comment]
脚本保持最新版，nikke画面设置要打开光晕效果和颜色分级，以上都不行请用模拟器截图并把原图发给我，在卡住的位置截图

**Comment by johnson50313** [comment]
就是卡这个确认介面，脚本确认最新，其他功能目前都能正常使用

**Comment by takagisanmie** [comment]
说了用模拟器截图，以文件的形式传上来

**Comment by takagisanmie** [comment]
你确定你的脚本是最新版吗，这里跟我一样吗
![image](https://github.com/user-attachments/assets/ab58511d-0af2-478d-80cc-3248fc078b3c)

**Comment by johnson50313** [comment]
版本一样，还是不行，但重新下载使用后就正常了
