### ISSUE TITLE
UI界面穿模优化

### ISSUE THREAD

**Issue by xianyu1124** [takagisanmie/NIKKEAutoScript#7]
![image](https://user-images.githubusercontent.com/36908318/225513704-67dcdbf4-b85b-48be-8f51-2b648b91d107.png)
商店处UI穿模了吧，还是我分辨率问题，我分辨率是2K。
还有一个问题，突然想到的。因为我能打开付费商店，所以每次升级会弹出一个限时商品，弹出的时候是否会点击关闭。（因为使用期间没遇到，不是很确定）
顺便推荐一个WIKI，说不定以后优化的时候能用上https://nikke.gamekee.com/

**Comment by takagisanmie** [comment]
我在收获奖励箱和通过企业塔时写了关闭限时商品，但是还没测试过，因为我这边用的是加速器，还麻烦你帮我留意下
穿模那里，我这边因为在编写的时后，没有把主程序缩的很窄，所以就没发现这个问题
我后面改短点

**Comment by takagisanmie** [comment]
我在收获奖励箱和通过企业塔时写了关闭限时商品，但是还没测试过，因为我这边用的是加速器，还麻烦你帮我留意下
穿模那里，我这边因为在编写的时后，没有把主程序缩的很窄，所以就没发现这个问题
我后面改短点

**Comment by takagisanmie** [comment]
加一下联系方法吧，我想详细看一下，可以吗

**Comment by xianyu1124** [comment]
用了几款自动工具，还是觉得你这款好用，就是分辨率方面有点没跟上，不过总体优化都是很好的，刚才升级后弹出限时商品，确定会自动关闭，暂未发现异常。
日常任务做完后希望增加点击收取每日奖励。辛苦了

**Comment by takagisanmie** [comment]
额

**Comment by xianyu1124** [comment]
Q2692452079

**Comment by takagisanmie** [comment]
收取每日奖励在任务‘每日任务’里

**Comment by takagisanmie** [comment]
搜不到欸，你加我的吧
3197137842
