### ISSUE TITLE
付费商店、商店

### ISSUE THREAD

**Issue by xiaglino** [takagisanmie/NIKKEAutoScript#8]
付费商店有了每日、每周、每月礼包功能；
普通商店购买0钻物品时会不断取消购买，一直循环。

**Comment by takagisanmie** [comment]
普通商店这个问题，我在多个账号都测试了，应该是没问题的，我nikke的画质开的最高，所有效果都是全开的。不知道是不是这个原因
付费商店的写了每日、每周的，但是没有测试，因为我用的是加速器，每月没写
你可以留一下联系方式，也方便交流
