### ISSUE TITLE
银华对话缺失

### ISSUE THREAD

**Issue by githubnano** [takagisanmie/NIKKEAutoScript#9]
银华
想休息一下。
好感+100 | ……
好感+50| 遇到什么麻烦了吗？
可以提requests吗，如果可以我有时间的话可以帮忙看看缺对话什么加进去

**Comment by takagisanmie** [comment]
因为银华的这段对话的+100选项，是省略号，没有识别到文字，目前这个方法比较蠢
我后面看看能不能改进下，requests的话随便提，没问题
